

      var toolbars = {
        title: 'Project Page',
        links: [{
          title:"Home Page",
          link:"/index.html",
        },]
      }

      var projects = [
      {
        id: 0,
        title:"Bluetooth-Controlled Car",
        text:"",
        purpose:"",
        backgroundImage:"assets/images/kevin/IMG_5804.JPG",
        actions:[{
            text:"",
            url:"",
            color:"",
        }],
        steps:[{
            image:"assets/images/steps/bc/1.png",
            title:"Step 1",
            text:"Ordering all parts",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/bc/2.png",
            title:"Step 2",
            text:"Attaching wheels",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/bc/3.png",
            title:"Step 3",
            text:"Connecting wires on the extension",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/bc/4.png",
            title:"Step 4",
            text:"Combining the extension and uno",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/bc/5.png",
            title:"Step 5",
            text:"adding the battery box",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/bc/6.png",
            title:"Step 6",
            text:"Coding on Arduino",
            // arrowsOrSlides: '',
        },
        ],
        description:"This is a Blutooth-controlled toy car. You can control it by connecting it with your cellphone using Bluetooth.",
        whatHaveILearned:"The idea came to my mind after I fixed my cousin's RC car bought from market that was poor in quality. I wanted to make a car that is essentially easier to control (since it does not need a old-school controller) and more portable. Designing it and teaching my cousin how to do troubleshooting was a memorable part in this experience.",
        image1:"assets/images/kevin/IMG_5783.JPG",
        image2:"assets/images/kevin/IMG_6000.JPG",
        image3:"assets/images/kevin/IMG_5785.JPG",
    },
      {
        id: 1,
        title:"Hand-control Car",
        text:"",
        purpose:"",
        backgroundImage:"assets/images/kevin/IMG_5749.JPG",
        actions:[{
            text:"",
            url:"",
            color:"",
        }],
        steps:[{
            image:"assets/images/steps/hc/1.png",
            title:"Step 1",
            text:"Ordering all parts",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/hc/2.png",
            title:"Step 2",
            text:"Attaching wheels and the motor module",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/hc/3.png",
            title:"Step 3",
            text:"Connecting wires on two main boards",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/hc/4.png",
            title:"Step 4",
            text:"Adding the battery box",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/hc/5.png",
            title:"Step 5",
            text:"Connecting wires on the Transmitter",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/hc/6.png",
            title:"Step 6",
            text:"Coding on Arduino",
            // arrowsOrSlides: '',
        },
        ],
        description:"This is an upgraded version of the Bluetooth-controlled car. For this RC car 2.0, you can controll it by moving one of your hands (with a Transimtter)in 4 directions, and the car will move according to your gesture.",
        whatHaveILearned:"The idea came from the inspiration that children do not always have access to phones. Therefore, this version allows children to control it using only their hands. It is more advanced and challenging because moving hands in different directions to control this car is a better illustration of interactions between humans and machines.",
        image1:"assets/images/kevin/IMG_5695.JPG",
        image2:"assets/images/kevin/IMG_5716.JPG",
        image3:"assets/images/kevin/IMG_5985.JPG",
    },
      {
        id: 2,
        title:"Tesla Coil",
        text:"",
        purpose:"",
        backgroundImage:"assets/images/kevin/IMG_5870.JPG",
        actions:[{
            text:"",
            url:"",
            color:"",
        }],
        steps:[{
            image:"assets/images/steps/tc/1.jpg",
            title:"Step 1",
            text:"How it works",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/tc/2.png",
            title:"Step 2",
            text:"Drawing the circuit diagram for the Tesla Coil",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/tc/3.png",
            title:"Step 3",
            text:"Buying certain circuit elements",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/tc/4.jpg",
            title:"Step 4",
            text:"Soldering",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/tc/5.png",
            title:"Step 5",
            text:"Attching circuit elements",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/tc/6.png",
            title:"Step 6",
            text:"Attching the cylinder with coils",
            // arrowsOrSlides: '',
        },
        ],
        description:"This is a miniature of the Tesla Coil invented in 1891 by Nikola Tesla. It can provide electricity without using wires by generating high voltage and transfering it through air. It can also create lightning effect on a small scale..",
        whatHaveILearned:"This was my very first experience of applying knowledge I learned from textbook to make actual products with my roommates. The original purpose of making this Tesla Coil was to provide light in our dormitory since our teachers prohibited us from bringing our own lamps. Also, I came to understand the difference between theories and practices, and it brought me the feeling of huge satisfactory and success after it worked.",
        image1:"assets/images/kevin/IMG_5853.JPG",
        image2:"assets/images/kevin/IMG_5842.JPG",
        image3:"assets/images/kevin/IMG_5872.JPG",
    },
      {
        id: 3,
        title:"Speakers",
        text:"",
        purpose:"",
        backgroundImage:"assets/images/kevin/IMG_5944.JPG",
        actions:[{
            text:"",
            url:"",
            color:"",
        }],
        steps:[{
            image:"assets/images/steps/s/1.png",
            title:"Step 1",
            text:"Baisc principle",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/s/2.png",
            title:"Step 2",
            text:"Circuit Diagram for the deputy board",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/s/3.png",
            title:"Step 3",
            text:"Circuit Diagram for the motherboard",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/s/4.png",
            title:"Step 4",
            text:"Ordering all parts",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/s/5.png",
            title:"Step 5",
            text:"Soldering",
            // arrowsOrSlides: '',
        },
        {
            image:"assets/images/steps/s/6.png",
            title:"Step 6",
            text:"Final Assembly",
            // arrowsOrSlides: '',
        },
        ],
        description:"This is a pair of dual track speakers. It is portable and good looking with its transparent shell. It carries a USB cable and a 3.5mm headphone cable, so it is compatible to most phones and laptops.",
        whatHaveILearned:"This is a group project that we worked on during 11th grade. The main theory of how speakers work is through electromagnetic induction, but it is harder to actually make a speaker since there are a lot of components to include. We consulted our teachers and other experts about signal processing and alternating currents and customized our PCB boards from an Elctronics company. It took us another week to assemble the speakers, but one of them did not work. Then, we used multimeter to detect where the problem was on the board. Ultimately, we successfully built our speakers. It was a hard-won but rewarding process in which I gained another experience of turning theories into practices and took me through an essential part in Engineering —— troubleshooting. ",
        image1:"assets/images/kevin/IMG_5950.JPG",
        image2:"assets/images/4-3.jpg",
        image3:"assets/images/kevin/IMG_5939.JPG",
    },
    ]

      var homepages = [{
        title:"Personal Space",
        text:"This is my personal space",
        backgroundImage:"http://picsum.photos/1000/600",
        titleOfBasicInformation:"Basic Information",
        textOfBasicInformation:"Basic Information Text",
      }]